"""Initial migration

Revision ID: 0ea819746dfe
Revises: 
Create Date: 2023-01-02 10:57:06.274792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea819746dfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kaggle_d1__fraud__data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('signup_time', sa.DateTime(), nullable=True),
    sa.Column('purchase_time', sa.DateTime(), nullable=True),
    sa.Column('purchase_value', sa.Float(), nullable=True),
    sa.Column('device_id', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=3), nullable=True),
    sa.Column('browser', sa.String(length=10), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.Float(), nullable=True),
    sa.Column('is_fraud', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kaggle_d1__fraud__data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kaggle_d1__fraud__data_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaggle_d1__fraud__data_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaggle_d1__fraud__data_signup_time'), ['signup_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaggle_d1__fraud__data_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaggle_d1__fraud__data_user_id'), ['user_id'], unique=False)

    op.create_table('kaggle_d1__ip_address__to__country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lower_bound_ip_address', sa.Integer(), nullable=True),
    sa.Column('upper_bound_ip_address', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kaggle_d1__ip_address__to__country', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kaggle_d1__ip_address__to__country_lower_bound_ip_address'), ['lower_bound_ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaggle_d1__ip_address__to__country_upper_bound_ip_address'), ['upper_bound_ip_address'], unique=False)

    op.create_table('kaggle_d2__online_fraud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('name_orig', sa.String(length=50), nullable=True),
    sa.Column('oldbalance_org', sa.Float(), nullable=True),
    sa.Column('newbalance_org', sa.Float(), nullable=True),
    sa.Column('name_dest', sa.String(length=50), nullable=True),
    sa.Column('oldbalance_dest', sa.Float(), nullable=True),
    sa.Column('newbalance_dest', sa.Float(), nullable=True),
    sa.Column('is_fraud', sa.Boolean(), nullable=True),
    sa.Column('is_flagged_fraud', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kaggle_d2__online_fraud', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kaggle_d2__online_fraud_is_fraud'), ['is_fraud'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaggle_d2__online_fraud_name_dest'), ['name_dest'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaggle_d2__online_fraud_name_orig'), ['name_orig'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaggle_d2__online_fraud_newbalance_dest'), ['newbalance_dest'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaggle_d2__online_fraud_newbalance_org'), ['newbalance_org'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaggle_d2__online_fraud_oldbalance_dest'), ['oldbalance_dest'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaggle_d2__online_fraud_oldbalance_org'), ['oldbalance_org'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaggle_d2__online_fraud_step'), ['step'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaggle_d2__online_fraud_type'), ['type'], unique=False)

    op.create_table('kaggle_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'name')
    )
    with op.batch_alter_table('kaggle_meta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kaggle_meta_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaggle_meta_value'), ['value'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kaggle_meta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kaggle_meta_value'))
        batch_op.drop_index(batch_op.f('ix_kaggle_meta_name'))

    op.drop_table('kaggle_meta')
    with op.batch_alter_table('kaggle_d2__online_fraud', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kaggle_d2__online_fraud_type'))
        batch_op.drop_index(batch_op.f('ix_kaggle_d2__online_fraud_step'))
        batch_op.drop_index(batch_op.f('ix_kaggle_d2__online_fraud_oldbalance_org'))
        batch_op.drop_index(batch_op.f('ix_kaggle_d2__online_fraud_oldbalance_dest'))
        batch_op.drop_index(batch_op.f('ix_kaggle_d2__online_fraud_newbalance_org'))
        batch_op.drop_index(batch_op.f('ix_kaggle_d2__online_fraud_newbalance_dest'))
        batch_op.drop_index(batch_op.f('ix_kaggle_d2__online_fraud_name_orig'))
        batch_op.drop_index(batch_op.f('ix_kaggle_d2__online_fraud_name_dest'))
        batch_op.drop_index(batch_op.f('ix_kaggle_d2__online_fraud_is_fraud'))

    op.drop_table('kaggle_d2__online_fraud')
    with op.batch_alter_table('kaggle_d1__ip_address__to__country', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kaggle_d1__ip_address__to__country_upper_bound_ip_address'))
        batch_op.drop_index(batch_op.f('ix_kaggle_d1__ip_address__to__country_lower_bound_ip_address'))

    op.drop_table('kaggle_d1__ip_address__to__country')
    with op.batch_alter_table('kaggle_d1__fraud__data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kaggle_d1__fraud__data_user_id'))
        batch_op.drop_index(batch_op.f('ix_kaggle_d1__fraud__data_source'))
        batch_op.drop_index(batch_op.f('ix_kaggle_d1__fraud__data_signup_time'))
        batch_op.drop_index(batch_op.f('ix_kaggle_d1__fraud__data_ip_address'))
        batch_op.drop_index(batch_op.f('ix_kaggle_d1__fraud__data_device_id'))

    op.drop_table('kaggle_d1__fraud__data')
    # ### end Alembic commands ###
