"""Initial migration

Revision ID: f2ff8dbabf1b
Revises: 
Create Date: 2023-01-07 22:46:09.054830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ff8dbabf1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kaggle_d1_fraud_data',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signup_time', sa.DateTime(), nullable=True),
    sa.Column('purchase_time', sa.DateTime(), nullable=True),
    sa.Column('purchase_value', sa.Float(), nullable=True),
    sa.Column('device_id', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=6), nullable=True),
    sa.Column('browser', sa.String(length=10), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.Float(), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=35), nullable=True),
    sa.Column('purchase_fingerprint', sa.String(length=35), nullable=True),
    sa.Column('is_fraud', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('kaggle_d1_fraud_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kaggle_d1_fraud_data_age'), ['age'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaggle_d1_fraud_data_browser'), ['browser'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaggle_d1_fraud_data_device_fingerprint'), ['device_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaggle_d1_fraud_data_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaggle_d1_fraud_data_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaggle_d1_fraud_data_purchase_fingerprint'), ['purchase_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaggle_d1_fraud_data_purchase_time'), ['purchase_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaggle_d1_fraud_data_signup_time'), ['signup_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_kaggle_d1_fraud_data_source'), ['source'], unique=False)

    op.create_table('kaggle_d1_ipaddress_to_country',
    sa.Column('lb_ip_address', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ub_ip_address', sa.BIGINT(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('lb_ip_address', 'ub_ip_address')
    )
    op.create_table('kaggle_d1_meta',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=75), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['kaggle_d1_fraud_data.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'name')
    )
    with op.batch_alter_table('kaggle_d1_meta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kaggle_d1_meta_value'), ['value'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kaggle_d1_meta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kaggle_d1_meta_value'))

    op.drop_table('kaggle_d1_meta')
    op.drop_table('kaggle_d1_ipaddress_to_country')
    with op.batch_alter_table('kaggle_d1_fraud_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kaggle_d1_fraud_data_source'))
        batch_op.drop_index(batch_op.f('ix_kaggle_d1_fraud_data_signup_time'))
        batch_op.drop_index(batch_op.f('ix_kaggle_d1_fraud_data_purchase_time'))
        batch_op.drop_index(batch_op.f('ix_kaggle_d1_fraud_data_purchase_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_kaggle_d1_fraud_data_ip_address'))
        batch_op.drop_index(batch_op.f('ix_kaggle_d1_fraud_data_device_id'))
        batch_op.drop_index(batch_op.f('ix_kaggle_d1_fraud_data_device_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_kaggle_d1_fraud_data_browser'))
        batch_op.drop_index(batch_op.f('ix_kaggle_d1_fraud_data_age'))

    op.drop_table('kaggle_d1_fraud_data')
    # ### end Alembic commands ###
